### ISSUE TITLE
mix ecto.setup errors

### ISSUE THREAD

**Issue by yyellowsun** [synterrr/ExChat#1]
How can I connect the chatroom to my pgsql?I creat a pgsql server，but can't connect it.

21:55:44.785 [error] GenServer #PID<0.401.0> terminating
** (Postgrex.Error) �������� 28P01 (invalid_password) �û� "postgres" Password ��֤ʧ��
    (db_connection 2.3.1) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Chat.Repo couldn't be created: killed

**Comment by synterrr** [comment]
You need to open pgAdmin and run the command mix ecto.create

**Comment by synterrr** [comment]
Your postgres password is not correct
